### PR TITLE
सबिन राई  album added

### PR DESCRIPTION
**Pull request by RupGautam**

### CODE REVIEW

**Comment by rhoit** [comment]
thanks a lot!

**Comment by RupGautam** [comment]
All lyrics are from same album not only guras ko. Here's itunes list: https://itunes.apple.com/us/album/sataha/id324145333

**Comment by rhoit** [comment]
@RupGautam yup, will be moved when, we sync them.. It will happen slowly..

**Comment by RupGautam** [comment]
@rhoit Got it.  
How are you guys syncing the lyric with time-stamp? Is there Linux application that make it easy? I don't have Linux machine yet.  
Btw I have been working on open data [Visualization Charts ](https://github.com/RupGautam/Chart_Nepal)using [Population Atlas of Nepal](http://cbs.gov.np/atlas/index.html). There's lot of open data which we can do something more for our community. Can I request my repo to be placed in @foss-np ? Or where can it be good place?

**Comment by rhoit** [comment]
@RupGautam I don't use any fancy stuff, just plain text editor, sadly it takes lots of time to get syncing right, Mostly its hit and trial..

I have yet to find good application for that..

I use [banshee](banshee.fm) and [osdlyrics](https://github.com/PedroHLC/osdlyrics) and text editor.

Nice Live charts, districts are better represented in **Map** something like [jQueryNepalViz](https://github.com/sul4bh/jQueryNepalViz).

Placing the project not the biggie,  either **admins** have to fork the project or you 
can transferee the ownership. What do you want to do! Hey admins! @krazedkrish @zerOnepal @samundra sort these this out...

**Comment by RupGautam** [comment]
Thanks @rhoit [jQueryNepalViz](https://github.com/sul4bh/jQueryNepalViz) is something I was looking before starting mine. 

I can transfer the ownership but I prefer admin to fork the repo.
Looking forward from @krazedkrish @zerOnepal and @samundra

**Pull request merged**
